name: BoundItems
main: com.dsdev.bounditems.BoundItems
version: 1.0
load: startup
commands:
   bind:
      description: The main command for BoundItems.
      usage: /<command> <subcommand> ...subcommand_args...
      permission: bounditems.bind
      permission-message: You don't have permission for this.